### PR TITLE
[Fix #8256] Fix an error for `--auto-gen-config` when running a cop without autocorrect

### LINKED ISSUE #8256: "undefined method `support_autocorrect?'" when using "--auto-gen-config"
While running `bundle exec rubocop --auto-gen-config`, I get an error after upgrading to 0.8.7. 

Might be related to the new changelog entries that handle autocorrect (#8164,  #8223, #8172).

Although, if I simply run `bundle exec rubocop`, there are no new offenses of any of these types. 

--------

## Expected behavior

While issuing the `bundle exec rubocop --auto-gen-config`, a .rubocop_todo.yml file should be generated, without producing errors. 

## Actual behavior

The command produces an error, here's the stacktrace:

```
undefined method `support_autocorrect?' for #<RuboCop::Cop::Naming::MethodName:0x00007ffa0f877600>
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/formatter/disabled_config_formatter.rb:118:in `output_cop_comments'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/formatter/disabled_config_formatter.rb:95:in `output_cop'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/formatter/disabled_config_formatter.rb:82:in `block in output_offenses'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/formatter/disabled_config_formatter.rb:81:in `each'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/formatter/disabled_config_formatter.rb:81:in `output_offenses'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/formatter/disabled_config_formatter.rb:52:in `finished'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/formatter/formatter_set.rb:33:in `block (3 levels) in <class:FormatterSet>'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/formatter/formatter_set.rb:33:in `each'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/formatter/formatter_set.rb:33:in `block (2 levels) in <class:FormatterSet>'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/runner.rb:84:in `inspect_files'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/runner.rb:39:in `run'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/cli/command.rb:10:in `run'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/cli/environment.rb:17:in `run'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/cli/command/auto_genenerate_config.rb:102:in `execute_runner'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/cli/command/auto_genenerate_config.rb:80:in `run_all_cops'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/cli/command/auto_genenerate_config.rb:24:in `run'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/cli/command.rb:10:in `run'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/cli/environment.rb:17:in `run'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/cli.rb:65:in `run_command'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/cli.rb:70:in `execute_runners'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/lib/rubocop/cli.rb:41:in `run'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/exe/rubocop:13:in `block in <top (required)>'
.../.rbenv/versions/2.6.6/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-0.87.0/exe/rubocop:12:in `<top (required)>'
.../.rbenv/versions/2.6.6/bin/rubocop:23:in `load'
.../.rbenv/versions/2.6.6/bin/rubocop:23:in `<top (required)>'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
.../.rbenv/versions/2.6.6/bin/bundle:23:in `load'
.../.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
```

.rubocop_todo.yml is still generated, but not complete. Starting anew with no todo file gives me the same behavior.

## Steps to reproduce the problem

On my codebase, this is triggered when I use: 

```bundle exec rubocop --auto-gen-config```

## RuboCop version

```
$ bundle exec rubocop -v
0.87.0
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #8256.

This PR fixes an error for `--auto-gen-config` when running a cop who do not support auto-correction.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/formatter/disabled_config_formatter.rb [hunk 1]
```diff
@@ -126,6 +125,13 @@ def output_cop_comments(output_buffer, cfg, cop_name, offense_count)
         output_cop_param_comments(output_buffer, params, default_cfg)
       end
 
+      def support_autocorrect?(cop_name)
+        cop_class = Cop::Cop.registry.find_by_cop_name(cop_name)
+        return false unless (cop_instance = cop_class&.new)
```
Comment (bbatsov) [inline lib/rubocop/formatter/disabled_config_formatter.rb:130]: I think it will read better if it says `unless cop_class` here. Then you won't need `&.` either when you're creating the cop instance.

File: lib/rubocop/formatter/disabled_config_formatter.rb [hunk 2]
```diff
@@ -126,6 +125,13 @@ def output_cop_comments(output_buffer, cfg, cop_name, offense_count)
...
+
+        cop_instance.respond_to?(:support_autocorrect?) && cop_instance.support_autocorrect?
```
Comment (bbatsov) [inline lib/rubocop/formatter/disabled_config_formatter.rb:132]: How come we have cops that don't support this method?

File: lib/rubocop/formatter/disabled_config_formatter.rb (hunk 1 above)
Comment (koic) [reply lib/rubocop/formatter/disabled_config_formatter.rb]: Ah, cool! I updated it.

File: lib/rubocop/formatter/disabled_config_formatter.rb (hunk 2 above)
Comment (koic) [reply lib/rubocop/formatter/disabled_config_formatter.rb]: `support_autocorrect?` is a class method, so `new` was not needed 💦

**Comment by bbatsov** [comment]
Thanks!

File: lib/rubocop/formatter/disabled_config_formatter.rb (hunk 2 above)
Comment (marcandre) [reply lib/rubocop/formatter/disabled_config_formatter.rb]: This is my mistake, I didn't see it. This is new since the Cop refactor.
Thanks @koic
